name: Hello World
on:
  push:
    branches:
      - main
      - develop
      - 'release/**'
      - 'feature/pr_demo'
  pull_request:
    types:
      - opened
    branches:
      - main
jobs:
  hello:
    runs-on: ubuntu-latest
    steps:
      - name: Hello Step
        run: echo "Welcome to GHA"
      - name: muiltiple hello step
        run: |
          echo "This is line one"
          echo "This is line two"
          echo "Hello, ${{vars.MY_NAME}}"
          echo "Docker password: ${{ secrets.DOCKER_PASSWORD }}"
      - name: Checkout source code
        uses: actions/checkout@v6
      - name: Print asp file content
        run: cat index.asp
  build:
    runs-on: ubuntu-latest
    needs: hello
    steps:
      - name: Build Step
        run: echo "A demo build"
  test:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Test Step
        run: echo "A demo test"

  deploy:
    runs-on: ubuntu-latest
    needs: test
    steps:
      - name: Deploy Step
        run: echo "A deploy test"
