name: Hello World
on: workflow_dispatch
jobs:
  hello:
    runs-on: ubuntu-latest
    steps:
      - name: Hello Step
        run: echo "Welcome to GHA"
      - name: muiltiple hello step
        run: |
          echo "This is line one"
          echo "This is line two"
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Build Step
        run: echo "A demo build"
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Test Step
        run: echo "A demo test"

  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Deploy Step
        run: echo "A deploy test"
    
